window.MANAGESAFETY_CONFIG = Object.freeze({
  "programName": "SafetyManage Mobile — Mining",
  "edition": "Guest Preview & Disabled Menus v4.1.1",
  "endpoint": "https://script.google.com/macros/s/AKfycby2F772UBGmJOmnOvwrzmlFYd1DNvbucufvo7IGtRiEGK3qz0dRSlHeTSSPSrl1gGpgdw/exec",
  "sponsor": "سعید دهیری ده نوی — سرپرست ایمنی معدن بنوید",
  "linkedinUrl": "https://www.linkedin.com/in/saeed-dahiri-dehnavi-668a0b173",
  "officialBrandWebsite": "https://sisoo.ir/",
  "publicBuild": true,
  "accessMode": "request-approval-or-reusable-code",
  "portfolioArchitecture": "central-control-and-separated-operational-sheets",
  "officialHoldingWebsite": "https://yazdfoulad.com/",
  "officialOperatingCompanyWebsite": "https://sisoo.ir/",
  "brandPolicy": "FOULAD_YAZD_HOLDING_AND_SISOO_OPERATING_LOCKED",
  "previewAccess": true,
  "professionalThemes": true,
  "dedicatedAdminKey": "PRIVATE_SERVER_SIDE_HASH_ONLY",
  "deploymentId": "AKfycby2F772UBGmJOmnOvwrzmlFYd1DNvbucufvo7IGtRiEGK3qz0dRSlHeTSSPSrl1gGpgdw",
  "guestPreviewWithoutRegistration": true,
  "guestCanBrowseOrganizations": true,
  "guestOperationsLocked": true
});
